services:
  - type: web
    name: finance-tracker-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8000
